# -*- coding: utf-8 -*-
"""bld.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iGF7BczLIQlVjv8JymSg68PFm_I3o0N6
"""



# =========================================================
# BUSINESS LOCATION DSS
# AUTA SHINTHA SARAH - PROJECT TPK
# =========================================================

# =========================================================
# INSTALL DEPENDENCIES
# =========================================================

!pip install -q streamlit plotly openpyxl pandas numpy scipy matplotlib seaborn

!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb

!dpkg -i cloudflared-linux-amd64.deb

# =========================================================
# CREATE PROJECT STRUCTURE
# =========================================================

import os

os.makedirs(
    "business-location-dss/modules",
    exist_ok=True
)

os.makedirs(
    "business-location-dss/ui",
    exist_ok=True
)

# =========================================================
# CONFIG
# =========================================================

config_code = '''
APP_TITLE = "🤎 Business Location DSS"

PAGE_ICON = "🤎"

COLORS = {
    "primary": "#6F4E37",
    "secondary": "#A67B5B",
    "background": "#F5ECE3",
    "card": "#FFFFFF",
    "text": "#3E2723"
}
'''

with open(
    "business-location-dss/config.py",
    "w"
) as f:

    f.write(config_code)

# =========================================================
# STYLES
# =========================================================

styles_code = '''
import streamlit as st
from config import COLORS

def load_css():

    st.markdown(f"""
    <style>

    .main {{
        background-color:
        {COLORS['background']};
    }}

    h1, h2, h3, h4, h5, h6 {{
        color:
        {COLORS['primary']} !important;
    }}

    p, div, span, label {{
        color:
        {COLORS['text']} !important;
    }}

    [data-testid="stSidebar"] {{
        background-color:
        {COLORS['secondary']};
    }}

    [data-testid="stSidebar"] * {{
        color: white !important;
    }}

    .stButton > button {{
        background-color:
        {COLORS['primary']};

        color: white !important;

        border-radius: 10px;

        border: none;

        font-weight: bold;
    }}

    .stMetric {{
        background-color: white;

        padding: 15px;

        border-radius: 15px;

        box-shadow:
        0px 2px 10px rgba(0,0,0,0.1);
    }}

    .stDataFrame {{
        border-radius: 15px;
    }}

    </style>
    """, unsafe_allow_html=True)
'''

with open(
    "business-location-dss/ui/styles.py",
    "w"
) as f:

    f.write(styles_code)

# =========================================================
# SIDEBAR
# =========================================================

sidebar_code = '''
import streamlit as st
import pandas as pd

def sidebar_menu():

    st.sidebar.title("🤎 Navigation")

    menu = st.sidebar.radio(
        "Select Module",
        [
            "🏠 Dashboard",
            "📊 Data-Driven DSS",
            "⚖️ Criteria Weight",
            "📋 Payoff Table",
            "🎲 EV & EOL",
            "❓ Uncertainty",
            "📈 Distribution",
            "⚖️ Utility Function",
            "🎰 Monte Carlo",
            "🏆 Recommendation"
        ]
    )

    st.sidebar.markdown("---")

    payoff_exists = (
        "payoff_df" in st.session_state
        and st.session_state["payoff_df"] is not None
        and isinstance(
            st.session_state["payoff_df"],
            pd.DataFrame
        )
        and not st.session_state["payoff_df"].empty
    )

    if payoff_exists:

        payoff_df = st.session_state["payoff_df"]

        st.sidebar.success(
            "✅ Payoff Connected"
        )

        st.sidebar.write(
            f"Alternatives: {payoff_df.shape[0]}"
        )

        st.sidebar.write(
            f"Criteria: {payoff_df.shape[1]}"
        )

    else:

        st.sidebar.warning(
            "⚠️ No Payoff Data"
        )

    return menu
'''

with open(
    "business-location-dss/ui/sidebar.py",
    "w"
) as f:

    f.write(sidebar_code)

# =========================================================
# DASHBOARD
# =========================================================

dashboard_code = '''
import streamlit as st

def show_dashboard():

    st.title("🤎 Business Location DSS")

    st.write("""
    Sistem Pendukung Keputusan
    untuk menentukan lokasi usaha terbaik
    menggunakan berbagai metode DSS.
    """)

    if (
        "payoff_df" in st.session_state
        and st.session_state["payoff_df"] is not None
    ):

        total_loc = len(
            st.session_state["payoff_df"]
        )

        total_state = len(
            st.session_state["payoff_df"].columns
        )

        status = "Connected"

    else:

        total_loc = 0
        total_state = 0
        status = "Waiting"

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric("📊 Modules", 10)

    with col2:
        st.metric("📍 Locations", total_loc)

    with col3:
        st.metric("🌎 Criteria", total_state)

    with col4:
        st.metric("🏆 Status", status)

    st.subheader("🚀 Workflow")

    st.info("""
    1. Upload dataset

    2. Generate payoff matrix

    3. Set criteria weights

    4. Run EV & EOL analysis

    5. Analyze uncertainty

    6. Distribution analysis

    7. Utility analysis

    8. Monte Carlo simulation

    9. Final recommendation
    """)


    st.subheader("🔗 System Connection")

    if status == "Connected":

        st.success("""
        ✅ Dataset Connected
        ✅ Payoff Matrix Connected
        ✅ All DSS Modules Connected
        """)

    else:

        st.warning("""
        ⚠️ Upload dataset terlebih dahulu untuk menghubungkan semua module DSS.
        """)

'''

with open(
    "business-location-dss/modules/dashboard.py",
    "w"
) as f:

    f.write(dashboard_code)

# =========================================================
# DATA DRIVEN DSS
# =========================================================

data_driven_code = '''
import streamlit as st
import pandas as pd
import plotly.express as px

def normalize_data(df):

    normalized_df = df.copy()

    for col in normalized_df.columns:

        min_val = normalized_df[col].min()
        max_val = normalized_df[col].max()

        if max_val - min_val != 0:

            normalized_df[col] = (
                (normalized_df[col] - min_val)
                /
                (max_val - min_val)
            )

    return normalized_df

def show_data_driven():

    st.title("📊 Data-Driven DSS")

    if "uploaded_df" not in st.session_state:
        st.session_state["uploaded_df"] = None

    if "payoff_df" not in st.session_state:
        st.session_state["payoff_df"] = None

    uploaded_file = st.file_uploader(
        "Upload Dataset",
        type=["csv", "xlsx"]
    )

    if uploaded_file is not None:

        try:

            if uploaded_file.name.endswith(".csv"):

                df = pd.read_csv(uploaded_file)

            else:

                df = pd.read_excel(uploaded_file)

            st.session_state["uploaded_df"] = df

            st.success(
                "✅ Dataset uploaded"
            )

        except Exception as e:

            st.error(f"❌ Error: {e}")

            return

    df = st.session_state["uploaded_df"]

    if df is not None:

        # =====================================
        # DATASET PREVIEW
        # =====================================

        st.subheader("📋 Dataset Preview")

        st.dataframe(
            df,
            use_container_width=True
        )

        # =====================================
        # BASIC INFO
        # =====================================

        col1, col2, col3 = st.columns(3)

        with col1:
            st.metric(
                "Rows",
                df.shape[0]
            )

        with col2:
            st.metric(
                "Columns",
                df.shape[1]
            )

        with col3:
            st.metric(
                "Numeric Features",
                len(
                    df.select_dtypes(
                        include="number"
                    ).columns
                )
            )

        numeric_cols = df.select_dtypes(
            include="number"
        ).columns

        # =====================================
        # DESCRIPTIVE STATISTICS
        # =====================================

        st.subheader(
            "📈 Descriptive Statistics"
        )

        st.dataframe(
            df.describe(),
            use_container_width=True
        )

        # =====================================
        # HISTOGRAM
        # =====================================

        st.subheader(
            "📊 Histogram Visualization"
        )

        selected_hist = st.selectbox(
            "Select Histogram Column",
            numeric_cols
        )

        fig_hist = px.histogram(
            df,
            x=selected_hist,
            color_discrete_sequence=["#6F4E37"]
        )

        st.plotly_chart(
            fig_hist,
            use_container_width=True
        )

        # =====================================
        # LOCATION COLUMN
        # =====================================

        location_col = st.selectbox(
            "Select Location Column",
            df.columns
        )

        # =====================================
        # BAR CHART
        # =====================================

        st.subheader(
            "📉 Bar Chart Visualization"
        )

        selected_bar = st.selectbox(
            "Select Bar Chart Column",
            numeric_cols,
            key="bar"
        )

        bar_data = (
            df.groupby(location_col)[selected_bar]
            .mean()
            .reset_index()
        )

        fig_bar = px.bar(
            bar_data,
            x=location_col,
            y=selected_bar,
            color=selected_bar,
            color_continuous_scale="Brwnyl"
        )

        st.plotly_chart(
            fig_bar,
            use_container_width=True
        )

        # =====================================
        # HEATMAP
        # =====================================

        st.subheader(
            "🔥 Correlation Heatmap"
        )

        corr = df[numeric_cols].corr()

        fig_heatmap = px.imshow(
            corr,
            text_auto=True,
            color_continuous_scale="Brwnyl"
        )

        st.plotly_chart(
            fig_heatmap,
            use_container_width=True
        )

        # =====================================
        # PAYOFF MATRIX
        # =====================================

        st.subheader(
            "🔄 Generate Payoff Matrix"
        )

        selected_metrics = st.multiselect(
            "Select Criteria",
            numeric_cols,
            default=list(numeric_cols[:3])
        )

        normalization = st.checkbox(
            "Apply Normalization"
        )

        if st.button(
            "Generate Payoff Matrix"
        ):

            payoff_df = df.set_index(
                location_col
            )[selected_metrics]

            if normalization:

                payoff_df = normalize_data(
                    payoff_df
                )

            st.session_state[
                "payoff_df"
            ] = payoff_df

            st.session_state[
                "alternatives"
            ] = payoff_df.index.tolist()

            st.session_state[
                "states"
            ] = payoff_df.columns.tolist()

            st.success(
                "✅ Payoff Matrix Generated"
            )

            st.subheader(
                "📋 Generated Payoff Matrix"
            )

            st.dataframe(
                payoff_df,
                use_container_width=True
            )

    else:

        st.info(
            "📂 Please upload dataset first."
        )
'''

with open(
    "business-location-dss/modules/data_driven.py",
    "w"
) as f:

    f.write(data_driven_code)

# =========================================================
# CRITERIA WEIGHT
# =========================================================

criteria_code = '''
import streamlit as st
import pandas as pd

def show_criteria_weight():

    st.title("⚖️ Criteria Weight")

    if (
        "payoff_df" not in st.session_state
        or st.session_state["payoff_df"] is None
    ):

        st.warning(
            "⚠️ Generate payoff matrix first."
        )

        return

    payoff_df = st.session_state["payoff_df"]

    weights = {}

    total = 0

    st.subheader(
        "📊 Set Criteria Weights"
    )

    for col in payoff_df.columns:

        default_value = round(
            1 / len(payoff_df.columns),
            2
        )

        weight = st.slider(
            f"{col}",
            0.0,
            1.0,
            default_value,
            0.01,
            key=f"weight_{col}"
        )

        weights[col] = weight

        total += weight

    st.info(
        f"Total Weight = {round(total,2)}"
    )

    if round(total,2) != 1.0:

        st.error(
            "⚠️ Total weight must equal 1.0"
        )

        return

    criteria_type = {}

    st.subheader(
        "⚖️ Criteria Type"
    )

    for col in payoff_df.columns:

        criteria_type[col] = st.selectbox(
            f"{col} Type",
            ["Benefit", "Cost"],
            key=f"type_{col}"
        )

    weighted_df = payoff_df.copy()

    for col in weighted_df.columns:

        if criteria_type[col] == "Cost":

            weighted_df[col] = (
                1 /
                (weighted_df[col] + 1e-9)
            )

        weighted_df[col] = (
            weighted_df[col]
            * weights[col]
        )

    st.session_state[
        "criteria_weights"
    ] = weights

    st.session_state[
        "criteria_type"
    ] = criteria_type

    st.session_state[
        "weighted_payoff_df"
    ] = weighted_df

    st.success(
        "✅ Weighted Matrix Saved"
    )

    st.dataframe(
        weighted_df,
        use_container_width=True
    )
'''

with open(
    "business-location-dss/modules/criteria_weight.py",
    "w"
) as f:

    f.write(criteria_code)

# =========================================================
# PAYOFF TABLE
# =========================================================

payoff_code = '''
import streamlit as st

def show_payoff_table():

    st.title("📋 Payoff Table")

    if (
        "weighted_payoff_df" in st.session_state
        and st.session_state["weighted_payoff_df"] is not None
    ):

        payoff_df = st.session_state[
            "weighted_payoff_df"
        ]

        st.success(
            "✅ Using Weighted Matrix"
        )

    elif (
        "payoff_df" in st.session_state
        and st.session_state["payoff_df"] is not None
    ):

        payoff_df = st.session_state[
            "payoff_df"
        ]

        st.warning(
            "⚠️ Using Original Matrix"
        )

    else:

        st.warning(
            "⚠️ No payoff matrix available."
        )

        return

    st.dataframe(
        payoff_df,
        use_container_width=True
    )
'''

with open(
    "business-location-dss/modules/payoff_table.py",
    "w"
) as f:

    f.write(payoff_code)

# =========================================================
# EV & EOL
# =========================================================

ev_code = '''
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px

def show_ev_eol():

    st.title("🎲 EV & EOL Analysis")

    if (
        "criteria_weights" not in st.session_state
    ):

        st.warning(
            "⚠️ Configure criteria weights first."
        )

        return

    if (
        "weighted_payoff_df" in st.session_state
        and st.session_state["weighted_payoff_df"] is not None
    ):

        payoff_df = st.session_state[
            "weighted_payoff_df"
        ]

    else:

        payoff_df = st.session_state[
            "payoff_df"
        ]

    weights = list(
        st.session_state[
            "criteria_weights"
        ].values()
    )

    st.subheader(
        "📊 Weighted Matrix"
    )

    st.dataframe(
        payoff_df,
        use_container_width=True
    )

    ev = payoff_df.dot(weights)

    ev_df = pd.DataFrame({

        "Alternative": payoff_df.index,

        "EV": np.round(
            ev.values,
            4
        )

    })

    ev_df = ev_df.sort_values(
        by="EV",
        ascending=False
    )

    st.subheader(
        "🎯 Expected Value"
    )

    st.dataframe(
        ev_df,
        use_container_width=True
    )

    regret = payoff_df.max() - payoff_df

    eol = regret.dot(weights)

    eol_df = pd.DataFrame({

        "Alternative": payoff_df.index,

        "EOL": np.round(
            eol.values,
            4
        )

    })

    eol_df = eol_df.sort_values(
        by="EOL",
        ascending=True
    )

    st.subheader(
        "📉 Expected Opportunity Loss"
    )

    st.dataframe(
        eol_df,
        use_container_width=True
    )

    st.success(
        f"🏆 Best EV : {ev.idxmax()}"
    )

    st.success(
        f"🏆 Best EOL : {eol.idxmin()}"
    )

    st.session_state[
        "ev_result"
    ] = ev.idxmax()

    st.session_state[
        "eol_result"
    ] = eol.idxmin()
'''

with open(
    "business-location-dss/modules/ev_eol.py",
    "w"
) as f:

    f.write(ev_code)

# =========================================================
# UNCERTAINTY
# =========================================================

uncertainty_code = '''
import streamlit as st
import pandas as pd

def show_uncertainty():

    st.title("❓ Uncertainty Analysis")

    if (
        "weighted_payoff_df" in st.session_state
        and st.session_state["weighted_payoff_df"] is not None
    ):

        payoff_df = st.session_state[
            "weighted_payoff_df"
        ]

    else:

        payoff_df = st.session_state[
            "payoff_df"
        ]

    maximax = payoff_df.max(axis=1)

    maximin = payoff_df.min(axis=1)

    laplace = payoff_df.mean(axis=1)

    regret = payoff_df.max() - payoff_df

    minimax = regret.max(axis=1)

    result = pd.DataFrame({

        "Location": payoff_df.index,

        "Maximax": maximax.values,

        "Maximin": maximin.values,

        "Laplace": laplace.values,

        "Minimax Regret": minimax.values

    })

    st.dataframe(
        result,
        use_container_width=True
    )

    st.success(
        f"🌟 Maximax : {maximax.idxmax()}"
    )

    st.success(
        f"🛡️ Maximin : {maximin.idxmax()}"
    )

    st.success(
        f"⚖️ Laplace : {laplace.idxmax()}"
    )

    st.success(
        f"📉 Minimax : {minimax.idxmin()}"
    )
'''

with open(
    "business-location-dss/modules/uncertainty.py",
    "w"
) as f:

    f.write(uncertainty_code)

# =========================================================
# DISTRIBUTION
# =========================================================

distribution_code = '''
import streamlit as st
import numpy as np
import plotly.express as px

def show_distribution():

    st.title("📈 Distribution Analysis")

    if (
        "weighted_payoff_df" not in st.session_state
        or st.session_state["weighted_payoff_df"] is None
    ):

        st.warning(
            "⚠️ Please generate weighted payoff matrix first."
        )

        return

    payoff_df = st.session_state[
        "weighted_payoff_df"
    ]

    location = st.selectbox(
        "Select Location",
        payoff_df.index
    )

    data = payoff_df.loc[location].values

    col1, col2 = st.columns(2)

    with col1:

        st.metric(
            "Mean",
            round(np.mean(data),4)
        )

    with col2:

        st.metric(
            "Standard Deviation",
            round(np.std(data),4)
        )

    fig = px.histogram(
        x=data,
        nbins=10,
        color_discrete_sequence=["#6F4E37"]
    )

    fig.update_layout(
        xaxis_title="Weighted Payoff",
        yaxis_title="Frequency"
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )

    st.success(
        "✅ Distribution analysis completed"
    )
'''

with open(
    "business-location-dss/modules/distribution.py",
    "w"
) as f:

    f.write(distribution_code)

# =========================================================
# UTILITY FUNCTION
# =========================================================

utility_code = '''
import streamlit as st
import numpy as np
import pandas as pd
import plotly.express as px

def show_utility():

    st.title("⚖️ Utility Function")

    if (
        "weighted_payoff_df" not in st.session_state
        or st.session_state["weighted_payoff_df"] is None
    ):

        st.warning(
            "⚠️ Please generate weighted payoff matrix first."
        )

        return

    payoff_df = st.session_state[
        "weighted_payoff_df"
    ]

    location = st.selectbox(
        "Select Location",
        payoff_df.index
    )

    values = payoff_df.loc[location].values

    risk = st.selectbox(
        "Risk Preference",
        [
            "Risk Averse",
            "Risk Neutral",
            "Risk Seeking"
        ]
    )

    x = np.linspace(
        min(values),
        max(values),
        100
    )

    if risk == "Risk Averse":

        utility = np.sqrt(
            x - min(x) + 1
        )

    elif risk == "Risk Neutral":

        utility = x

    else:

        utility = (
            x - min(x) + 1
        ) ** 2

    df = pd.DataFrame({

        "Payoff": x,

        "Utility": utility

    })

    fig = px.line(
        df,
        x="Payoff",
        y="Utility",
        color_discrete_sequence=["#6F4E37"]
    )

    fig.update_layout(
        xaxis_title="Weighted Payoff",
        yaxis_title="Utility Value"
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )

    st.success(
        f"✅ Expected Utility = {round(np.mean(utility),4)}"
    )
'''

with open(
    "business-location-dss/modules/utility.py",
    "w"
) as f:

    f.write(utility_code)

# =========================================================
# MONTE CARLO
# =========================================================

monte_code = '''
import streamlit as st
import numpy as np
import plotly.express as px

def show_monte_carlo():

    st.title("🎰 Monte Carlo Simulation")

    if (
        "weighted_payoff_df" not in st.session_state
        or st.session_state["weighted_payoff_df"] is None
    ):

        st.warning(
            "⚠️ Please generate weighted payoff matrix first."
        )

        return

    payoff_df = st.session_state[
        "weighted_payoff_df"
    ]

    location = st.selectbox(
        "Select Location",
        payoff_df.index
    )

    values = payoff_df.loc[location].values

    simulations = st.slider(
        "Number of Simulations",
        100,
        10000,
        1000
    )

    simulated = np.random.normal(
        np.mean(values),
        np.std(values),
        simulations
    )

    col1, col2 = st.columns(2)

    with col1:

        st.metric(
            "Expected Profit",
            round(np.mean(simulated),4)
        )

    with col2:

        st.metric(
            "Simulation Std",
            round(np.std(simulated),4)
        )

    fig = px.histogram(
        simulated,
        nbins=40,
        color_discrete_sequence=["#6F4E37"]
    )

    fig.update_layout(
        xaxis_title="Simulated Profit",
        yaxis_title="Frequency"
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )

    prob_profit = (
        np.mean(simulated > 0)
        * 100
    )

    st.success(
        f"✅ Probability of Profit = {round(prob_profit,2)}%"
    )
'''

with open(
    "business-location-dss/modules/monte_carlo.py",
    "w"
) as f:

    f.write(monte_code)

# =========================================================
# RECOMMENDATION ENGINE
# =========================================================

recommendation_code = '''
import streamlit as st
import pandas as pd

def show_recommendation():

    st.title("🏆 Recommendation Engine")

    if (
        "weighted_payoff_df" in st.session_state
        and st.session_state["weighted_payoff_df"] is not None
    ):

        payoff_df = st.session_state[
            "weighted_payoff_df"
        ]

    else:

        payoff_df = st.session_state[
            "payoff_df"
        ]

    weights = list(
        st.session_state[
            "criteria_weights"
        ].values()
    )

    maximax = payoff_df.max(axis=1)

    maximin = payoff_df.min(axis=1)

    laplace = payoff_df.mean(axis=1)

    regret = payoff_df.max() - payoff_df

    minimax = regret.max(axis=1)

    ev = payoff_df.dot(weights)

    best_maximax = maximax.idxmax()

    best_maximin = maximin.idxmax()

    best_laplace = laplace.idxmax()

    best_minimax = minimax.idxmin()

    best_ev = ev.idxmax()

    votes = [

        best_maximax,

        best_maximin,

        best_laplace,

        best_minimax,

        best_ev

    ]

    result = pd.Series(
        votes
    ).value_counts()

    final_choice = result.idxmax()

    df = pd.DataFrame({

        "Method": [

            "Maximax",

            "Maximin",

            "Laplace",

            "Minimax Regret",

            "Expected Value"

        ],

        "Recommendation": votes

    })

    st.dataframe(
        df,
        use_container_width=True
    )

    st.success(
        f"🏆 Final Recommendation : {final_choice}"
    )

    st.info(
        f"Selected by {result.max()} methods"
    )
'''

with open(
    "business-location-dss/modules/recommendation_engine.py",
    "w"
) as f:

    f.write(recommendation_code)

# =========================================================
# MAIN APP
# =========================================================

app_code = '''
import streamlit as st

from config import APP_TITLE, PAGE_ICON

from ui.styles import load_css
from ui.sidebar import sidebar_menu

from modules.dashboard import show_dashboard
from modules.data_driven import show_data_driven
from modules.criteria_weight import show_criteria_weight
from modules.payoff_table import show_payoff_table
from modules.ev_eol import show_ev_eol
from modules.uncertainty import show_uncertainty
from modules.distribution import show_distribution
from modules.utility import show_utility
from modules.monte_carlo import show_monte_carlo
from modules.recommendation_engine import show_recommendation

st.set_page_config(
    page_title=APP_TITLE,
    page_icon=PAGE_ICON,
    layout="wide"
)

load_css()

menu = sidebar_menu()

if menu == "🏠 Dashboard":

    show_dashboard()

elif menu == "📊 Data-Driven DSS":

    show_data_driven()

elif menu == "⚖️ Criteria Weight":

    show_criteria_weight()

elif menu == "📋 Payoff Table":

    show_payoff_table()

elif menu == "🎲 EV & EOL":

    show_ev_eol()

elif menu == "❓ Uncertainty":

    show_uncertainty()

elif menu == "📈 Distribution":

    show_distribution()

elif menu == "⚖️ Utility Function":

    show_utility()

elif menu == "🎰 Monte Carlo":

    show_monte_carlo()


elif menu == "🏆 Recommendation":

    show_recommendation()
'''

with open(
    "business-location-dss/app.py",
    "w"
) as f:

    f.write(app_code)

# =========================================================
# RUN STREAMLIT
# =========================================================

!pkill streamlit

!streamlit run business-location-dss/app.py &>/content/logs.txt &

print("🚀 BUSINESS LOCATION DSS RUNNING...")
print("⏳ WAIT 15-30 SECONDS...")

# =========================================================
# PUBLIC URL
# =========================================================

!cloudflared tunnel --url http://localhost:8501